### ISSUE TITLE
Feature request:  Make "Comment" span over more lines

### ISSUE THREAD

**Issue by revast** [linux-man/ezame#7]
Hello,
First of all, thanks for EZAME!!

I would like to propose that the Comment line could be a bigger area where one can actually type a text in, not just one line. As it's the last item in the properties tab, there would be space to do so.

**Comment by linux-man** [comment]
Thanks for using it!
That is an interesting request, but I'm inclined to reject your proposal. Here's why:
- Ezame don't try to hide the intricacies of the desktop file. Since 'comment' is a one-line entry (like the rest), I prefer to show it that way.
- I searched, and on 400+ desktop files I have, not one has a multiline comment. There must be a reason for that. I can confirm that Cinnamon Menu does a bad work with multiline comments. I wouldn't like to promote that.
- [Desktop Entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) accept escape sequences ( \s, \n, \t, \r, and \\\\), so the way to create a new line is to use '\n'. You can do what you want IF you know what you're doing.

That's the main philosophy of Ezame - an editor for Power users.
Fell free to disagree and counter-argument. :wink:

**Comment by revast** [comment]
ok, I understand. I use this quite extensively, as I also build my own menu. As I do this all manually, ezame is quite a refreshing help and I can browse quickly through my .desktop files to see if something is missing. As I can also edit the text in last tab, this is ok for me.
