### ISSUE TITLE
Add a better way to select images and open local file.desktop

### ISSUE THREAD

**Issue by brunodavi** [linux-man/ezame#8]
I really liked this menu editor, but I would like to improve the way of adding the images, perhaps similar to the `menulibre` which is fast in loading and practical when selecting the image, and also that a button is added to open the file location for when it is necessary to delete .desktop

And thanks for creating this application

**Comment by linux-man** [comment]
Obrigado for your sugestions.
I'm looking at how menulibre and cinnamon-menu-editor are calling that nice icon search dialog - and if it's a system dialog.
About deleting - Ezame can delete local desktop files on Ficheiros menu. I don't want to give an option to delete global files - it's better to disable them.

**Comment by linux-man** [comment]
I found that my favourite icon picker (https://winaero.com/blog/wp-content/uploads/2018/10/xapp-icon-chooser.png) is a XApp component, so it's Cinnamon exclusive. Sad.
Best bet, since I don't want to reinvent the wheel, is to adapt https://github.com/Tomha/python-gtk-themed-icon-chooser.
I'll be looking at that.

**Comment by linux-man** [comment]
What about 5fc1b6f16e27f913740dbc7157ff7da24a5b02b6?
